<?PHP 
// Display candidates in "Browse by Position" Page
$isdisplaycand = "N";

// Current Term of President
$pterm = 2001;
$ptermend = 2004;

// Current Term of Vice President
$vpterm = 2001;
$vptermend = 2004;

// Term of 1st Batch Senators
$term1st = 1998;
// Term of 2nd Batch Senators
$term2nd = 2001;

// Term of Governor
$govterm = 2001;
$govtermend = 2004;

// Term of Vice Governor
$vicegovterm = 2001;
$vicegovtermend = 2004;

// Term of Provincial Board Members
$provterm = 2001;
$provtermend = 2004;

// Term of House Representatives
$repterm = 2001;
$reptermend = 2004;

// Term of Mayor
$mayterm = 2001;
$maytermend = 2004;

// Term of Vice Mayor
$vmayterm = 2001;
$vmaytermend = 2004;

// Term of Councilors
$counterm = 2001;
$countermend = 2004;
?>