<DIV ALIGN="LEFT">
<P CLASS="RIGHTBOXFONT">
The list of representatives is now updated. Only those party-list representatives are not on the list.
</P>
</DIV>
<HR WIDTH="50%" SIZE="1" NOSHADE>
<DIV ALIGN="CENTER">
<A HREF="/vote/electresults/candpartylist.php">PARTY-LIST ELECTION RESULTS</A><BR><BR>
<A HREF="/vote/electresults/candpartylistbreakdown.php" CLASS="RIGHTBOXFONT">(w/ regional breakdown)</A><BR>
</DIV>
</P>
<HR WIDTH="50%" SIZE="1" NOSHADE>
<P CLASS="RIGHTBOXFONT">
<B>Food for the Thought Articles</B><BR>
  <A HREF="/vote/attachments/desiretoserve.html">The Desire to Serve</A><BR>
  <A HREF="/vote/attachments/freedom.html">Freedom, Power and Responsibility</A>
  <A HREF="/vote/attachments/moralitypartI.html">Morality: A Problem of the Nation, Part I</A><BR>
  <A HREF="/vote/attachments/moralitypartII.html">Morality: A Problem of the Nation, Part II</A><BR>
  <A HREF="/vote/attachments/hopeandfrustration.html">Hope and Frustration</A><BR>
<A HREF="/vote/attachments/terrorism.html">Terrorism</A><BR>
</P>
