<SCRIPT LANGUAGE="javascript">
<!--
	function mouse_ovr(src,colorover) {
  		if (!src.contains(event.fromElement)) {
    		src.style.cursor = 'hand'; 
			src.bgColor = colorover;
  		}
	}
	function mouse_out(src,colorin) {
  		if (!src.contains(event.toElement)) {
    		src.style.cursor = 'default';
    		src.bgColor = colorin;
  		}
	}
	function go_location(src,location) {
  		if (!src.contains(event.toElement)) {
    		window.location.href = location;
  		}
	}
-->	
</SCRIPT>
<TABLE WIDTH="100%" BORDER="0" CELLSPACING="0" CELLPADDING="0" ALIGN="center" STYLE="border-width: 1px 1px 1px 1px;">
	<TR><TD BGCOLOR="#8DC1FC">&nbsp;
	</TD></TR>
	<TR><TD>
	   <TABLE WIDTH="100%" BORDER="0" CELLSPACING="0" CELLPADDING="0" ALIGN="center"><TR BGCOLOR="RED">	  
	   <TD WIDTH="10%" ALIGN="center">&nbsp;</TD>
	   <TD ALIGN="center" onClick="go_location(this,'/vote/')" onMouseOver="mouse_ovr(this,'#168AFF')" onMouseOut="mouse_out(this,'Red')">			
	      <A HREF="/vote/" STYLE="color: White;" TITLE="Vote.ph Home Page"><B>Home</B></A>
	   </TD>	
	   <TD ALIGN="center" onClick="go_location(this,'/vote/about/')" onMouseOver="mouse_ovr(this,'#168AFF')" onMouseOut="mouse_out(this,'Red')">	
			<A HREF="/vote/about/" STYLE="color: White;" TITLE="What is vote.ph and how it aims to help the Filipino voters"><B>About</B></A>
	   </TD>	
	   <TD ALIGN="center" onClick="go_location(this,'/vote/search/search.php')" onMouseOver="mouse_ovr(this,'#168AFF')" onMouseOut="mouse_out(this,'Red')">	
			<A HREF="/vote/search/search.php" STYLE="color: White;" TITLE="Search this site!"><B>Search</B></A>
	   </TD>	
	   <TD ALIGN="center" onClick="go_location(this,'/vote/feedback/feedback.php')" onMouseOver="mouse_ovr(this,'#168AFF')" onMouseOut="mouse_out(this,'Red')">	
			<A HREF="/vote/feedback/feedback.php" STYLE="color: White;" TITLE="Help us to improve! Send us your thoughts about vote.ph!"><B>Feedback</B></A>
	   </TD>	
	   <TD ALIGN="center" onClick="go_location(this,'/vote/legal/')" onMouseOver="mouse_ovr(this,'#168AFF')" onMouseOut="mouse_out(this,'Red')">	
			<A HREF="/vote/legal/" STYLE="color: White;" TITLE="Copyright, Privacy Statement, Disclaimers, etc."><B>Legal Info</B></A>
		</TD>
	   <TD ALIGN="center" onClick="go_location(this,'/vote/feedback/emailtofriend.php')" onMouseOver="mouse_ovr(this,'#168AFF')" onMouseOut="mouse_out(this,'Red')">	
			<A HREF="/vote/feedback/emailtofriend.php" STYLE="color: White;" TITLE="Help us promote our site. Email this page to all your friends!"><B>Email to friends</B></A>
		</TD>		
	   <TD ALIGN="center" onClick="go_location(this,'/vote/special/links.php')" onMouseOver="mouse_ovr(this,'#168AFF')" onMouseOut="mouse_out(this,'Red')">	
			<A HREF="/vote/special/links.php" STYLE="color: White;" TITLE="View directory of external links"><B>Links</B></A>
		</TD>		

		<TD WIDTH="10%" ALIGN="center">&nbsp;</TD>
		</TR></TABLE>
	</TD></TR>	
	<TR><TD>&nbsp;
	</TD></TR>
	<TR><TD>		
	      <DIV ALIGN="CENTER">
			<SPAN CLASS="COPYRIGHT"><A HREF="/vote/legal/copyright.php">Copyright</A> &#169; 2001 FilWorld PH, Inc. All rights
				reserved.&nbsp;Read our <A HREF="/vote/legal/disclaimer.php">legal disclaimer</A>.<BR>
				Email us at <A HREF="mailto:info@vote.ph">info@vote.ph</A>.<BR>
			</SPAN>
		</DIV>		
	</TD></TR>	
</TABLE>	
	