<META NAME="Description" CONTENT="Vote.ph is the Philippine's online directory and resource center for all incumbent government officials and election candidates from the president down to the councilor, from Aparri until Sulu.">
<META NAME="Keywords" CONTENT="vote, politics, election, polls, people empowerment, philippine election, political parties">
<META NAME="Author" CONTENT="Washington Alto">
<META NAME="Reply-to" CONTENT="washingtonalto@yahoo.com">
<META HTTP-EQUIV="Expires" CONTENT="0">
<META HTTP-EQUIV="Pragma" CONTENT="no-cache">
<META HTTP-EQUIV="Cache-Control" CONTENT="no-cache">
<LINK HREF="/vote/css/vote.css" REL="stylesheet" TYPE="text/css" TITLE="Vote.ph Default Stylesheet">
<LINK HREF="mailto:washingtonalto@yahoo.com" REV="made" TITLE="editor-in-chief of Vote.ph">
<LINK HREF="/" REL="home" TITLE="Vote.ph home page">
<BASE Target="_top"> <!-- Frame-proof this site -->
